version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IKHsgNJffurME1E6GueP
      POSTGRES_DB: traffic_flow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: streamlit_app
    environment:
      # IMPORTANT: Point to the database container using its service name "db"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: traffic_flow_db
      DB_USER: postgres
      DB_PASSWORD: IKHsgNJffurME1E6GueP
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  postgres_data:

