name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # Runs on push to master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Google Cloud SDK
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/truck_flow_app/truck-flow-app:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/truck_flow_app/truck-flow-app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy truck-flow-app \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/truck_flow_app/truck-flow-app:latest \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated

