name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master  # Change this if your main branch is named differently
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Google Cloud SDK
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/truck-flow-app:latest .
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/truck-flow-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy truck-flow-app \
            --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/truck-flow-app:latest \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated
